name: "Deploy Dashboard — Retomada"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-s3-cloudfront.yml
    with:
      client_name: "retomada"
      environment: "production"
      s3_bucket: "web-pj-retomada-prod-385697366782"
      cloudfront_distribution_id: "EXICSF7F6H51S"
      aws_region: "sa-east-1"
      react_app_api_url: "https://d1qps131f72hsm.cloudfront.net/api"
      react_app_front_app: "retomada"
      react_app_title: "Retomada"
      react_app_description: "Dashboard da prefeitura de Retomada"
      react_app_sga_api_base_url: "https://sandbox.sga.integrapay.com.br/api"
    secrets: inherit
