name: "Deploy Dashboard — AmazonBank"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-s3-cloudfront.yml
    with:
      client_name: "amazonbank"
      environment: "production"
      s3_bucket: "web-pj-amazonbank-prod-385697366782"
      cloudfront_distribution_id: "E1R43ODMRZPL1S"
      aws_region: "sa-east-1"
      react_app_api_url: "https://d1iu1sqxrro1a.cloudfront.net/api"
      react_app_front_app: "amazonbank"
      react_app_title: "AmazonBank"
      react_app_description: "Amazon Banking Trust - Dashboard do Banco Amazon Banking Trust"
    secrets: inherit
