name: "Deploy Dashboard — Itapuranga"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-s3-cloudfront.yml
    with:
      client_name: "itapuranga"
      environment: "production"
      s3_bucket: "web-pj-itapuranga-prod-385697366782"
      cloudfront_distribution_id: "E3NOSPSAPP12A5"
      aws_region: "sa-east-1"
      react_app_api_url: "https://dex1mifd6pkj3.cloudfront.net/api"
      react_app_front_app: "itapuranga"
      react_app_title: "Itapuranga"
      react_app_description: "Dashboard da prefeitura de Itapuranga"
      react_app_sga_api_base_url: "https://sandbox.sga.integrapay.com.br/api"
    secrets: inherit
