name: "Deploy Dashboard — PMGO"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-s3-cloudfront.yml
    with:
      client_name: "pmgo"
      environment: "production"
      s3_bucket: "web-pj-pmgo-prod-385697366782"
      cloudfront_distribution_id: "E1SQBVQ30P9H1T"
      aws_region: "sa-east-1"
      react_app_api_url: "https://d1wu61luekx972.cloudfront.net/api"
      react_app_front_app: "pmgo"
      react_app_title: "PMGO"
      react_app_description: "Dashboard da Polícia Militar do Estado de Goiás - PMGO"
      react_app_sga_api_base_url: "https://sandbox.sga.integrapay.com.br/api"
    secrets: inherit
