name: "Deploy Dashboard — Itaberaí"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-s3-cloudfront.yml
    with:
      client_name: "itaberai"
      environment: "production"
      s3_bucket: "web-pj-itaberai-prod-385697366782"
      cloudfront_distribution_id: "E1L9ST7UZNJFB5"
      aws_region: "sa-east-1"
      react_app_api_url: "https://dl479dur2w5rx.cloudfront.net/api"
      react_app_front_app: "itaberai"
      react_app_title: "Itaberai"
      react_app_description: "Dashboard da prefeitura de Itaberaí"
      react_app_sga_api_base_url: "https://sandbox.sga.integrapay.com.br/api"
    secrets: inherit
