name: "Portal — Deploy Corumbaíba"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-s3-cloudfront.yml
    with:      
      client_name: "corumbaiba"
      environment: "production"
      s3_bucket: "portal-corumbaiba-prod-385697366782"
      cloudfront_distribution_id: "E3U476870I87MY"
      aws_region: "sa-east-1"
      react_app_api_url: "https://api.go.inttegrasocial.com.br/api"
      react_app_front_app: "corumbaiba"
      react_app_title: "Corumbaiba"
      react_app_description: "Dashboard da prefeitura de Corumbaíba"
      react_app_sga_api_base_url: "https://sandbox.sga.integrapay.com.br/api"
    secrets: inherit
