name: "Portal — Deploy SEAPA"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-s3-cloudfront.yml
    with:
      client_name: "seapa"
      environment: "production"
      s3_bucket: "portal-seapa-prod-385697366782"
      cloudfront_distribution_id: "E8DQZFB29ZRVJ"
      aws_region: "sa-east-1"
      react_app_api_url: "https://api.go.inttegrasocial.com.br/api"
      react_app_front_app: "seapa"
      react_app_title: "SEAPA"
      react_app_description: "Dashboard da Secretaria de Estado de Agricultura, Pecuária e Abastecimento - SEAPA"
      react_app_sga_api_base_url: "https://sandbox.sga.integrapay.com.br/api"
    secrets: inherit
