name: "Portal — Deploy AmazonBank"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-s3-cloudfront.yml
    with:
      client_name: "amazonbank"
      environment: "production"
      s3_bucket: "portal-amazonbank-prod-385697366782"
      cloudfront_distribution_id: "E20Z16ASFX9913"
      aws_region: "sa-east-1"
      react_app_api_url: "https://api.go.inttegrasocial.com.br/api"
      react_app_front_app: "amazonbank"
      react_app_title: "AmazonBank"
      react_app_description: "Amazon Banking Trust - Dashboard do Banco Amazon Banking Trust"
      react_app_sga_api_base_url: "https://sandbox.sga.integrapay.com.br/api"
    secrets: inherit
